version: '3.7'

services:

  prometheus:
    image: prom/prometheus
    container_name: 'scaling_prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    container_name: 'scaling_grafana'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - '3000:3000'

  blocking-io:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-blocking-io
    environment:
      BLOCKING: "io"
      # IO blocking is in units of Millis
      IO_MAX_BLOCK: 100 # 10 millis
      IO_MIN_BLOCK: 10  # 1 milli

      THREADING: "single"
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 1

  blocking-cpu:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-blocking-cpu
    environment:
      BLOCKING: "cpu"
      # CPU blocking is in units of Micros
      CPU_MAX_BLOCK: 100000 # 100 millis
      CPU_MIN_BLOCK: 10000  # 10 milli

      THREADING: "single"
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 1
