version: '3.7'

services:

  prometheus:
    image: prom/prometheus
    container_name: 'scaling_prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    container_name: 'scaling_grafana'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - '3000:3000'

  multi-0:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-0
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4

  multi-1:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-1
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4

  multi-2:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-2
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4


  multi-3:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-3
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4

  multi-4:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-4
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4

  multi-5:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-5
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4

  multi-6:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-6
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4


  multi-7:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-7
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4

  multi-8:
    image: blocking:1.0-SNAPSHOT
    container_name: observability-multi-horizontal-8
    environment:
      BLOCKING: "real"
      MAX_BLOCK: 1
      MIN_BLOCK: 0

      THREADING: "queue"
      THREADS: 400
    expose:
      - 8080
    deploy:
      resources:
        limits:
          cpus: 4