{
 "title": "Blocking",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Operations Processed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(loop_timer_seconds_count[1m])) by (blocking)",
     "legendFormat": "{{blocking}}"
    }
   ]
  },
  {
   "title": "Processing  Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "max(loop_timer_seconds_max)", "legendFormat": "max" },
    {
     "expr": "avg(rate(loop_timer_seconds_sum [1m])/ rate(loop_timer_seconds_count [1m])) by (job, blocking)",
     "legendFormat": "{{job}}-{{blocking}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}